version: "3.8"
services:
  mongodb:
    image: mongo
    container_name: voting-mongodb
    environment:
      - MONGO_INITDB_DATABASE=voting-secredi
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=RootSicredi
    volumes:
      - ./data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d/:ro
    ports:
      - 27017:27017
    restart: always